group = cz.basicland.mc

mcVersion = 1.21.10
version = 1.21.10-R0.1-SNAPSHOT
divineRef = 5e09823753e731efa92c9e4289e61fc7bcef8989
experimental = false
publishDevBundle = true

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
