group = cz.basicland.mc
version = 26.2-SNAPSHOT

mcVersion = 26.2
apiVersion = 26.2
divineRef = c6af7e434fc78ee50536aa5c75aaf7cf8dd5b72a
channel = STABLE
publishDevBundle = true

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
