group = cz.basicland.mc

mcVersion = 1.21.4
version = 1.21.4-R0.1-SNAPSHOT
divineRef = 9ecce7b5df44eaca96503e6a2b4bbb612c9e5694
experimental = false
publishDevBundle = true

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
